// Regression tests for the 2026-05-22 multi-team credit-export shape, the
// multi-dimensional opportunity-name routing, and the historical-baseline
// ingest path.
//
// SOPs:
//   - architecture/sop_volunteer_credit_routing.md
//   - architecture/sop_historical_baseline_ingest.md
//   - architecture/sop_metrics_and_good_standing.md

import { describe, it, expect } from 'vitest';
import * as XLSX from 'xlsx';
import { writeFileSync, mkdirSync, rmSync, renameSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  parseVolunteerCredit,
  type CashRoutingRule,
  type CreditRoutingPattern,
} from '../src/parse_volunteer_credit.js';
import { computeMetrics } from '../src/compute_metrics.js';
import {
  computeHistoricalBaseline,
  isHistoricalFile,
} from '../src/compute_historical_baseline.js';
import { IngestErrorCollector } from '../src/ingest_errors.js';
import type { Roster, RosterRow } from '../src/types.js';

const here = dirname(fileURLToPath(import.meta.url));
const TMP = resolve(here, 'codex_tmp');
mkdirSync(TMP, { recursive: true });

// ─── Helpers ──────────────────────────────────────────────────────────────

function row(overrides: Partial<RosterRow>): RosterRow {
  return {
    full_contact_id: null,
    sales_rep_id: null,
    first_name: 'X',
    last_name: 'Y',
    full_name: 'X Y',
    email: null,
    phone: null,
    team: null,
    is_sales_captain: false,
    member_type: 'Yellow Jacket',
    active: true,
    first_year_of_volunteering: null,
    fiesta_ticket_link: null,
    rate_ticket_link: null,
    last_year_fundraising_dollars: null,
    last_year_fundraising_rank: null,
    job: null,
    ...overrides,
  };
}

function makeRoster(rows: RosterRow[]): Roster {
  return {
    rows,
    by_full_contact_id: new Map(
      rows.filter((r) => r.full_contact_id).map((r) => [r.full_contact_id!, r]),
    ),
    by_sales_rep_id: new Map(
      rows.filter((r) => r.sales_rep_id != null).map((r) => [r.sales_rep_id!, r]),
    ),
  };
}

const SEEDS_BASE: CashRoutingRule[] = [
  { type: '*', opportunity_name_pattern: '2025 FKE Paddle Raise', routing: 'dollars',
    routing_metrics: ['total_fundraising', 'total_points'] },
  { type: '*', opportunity_name_pattern: 'Race for Wishes', routing: 'dollars',
    routing_metrics: ['total_fundraising', 'wishes_for_teachers', 'total_points'] },
  { type: '*', opportunity_name_pattern: '2025 Future Dues', routing: 'dollars',
    routing_metrics: ['total_fundraising', 'total_points'] },
  { type: '*', opportunity_name_pattern: 'Fiesta Sports Foundation - Donation', routing: 'dollars',
    routing_metrics: ['total_fundraising', 'total_points'] },
  { type: '*', opportunity_name_pattern: '2025 Par 3 - Silent Auction', routing: 'dollars',
    routing_metrics: ['total_fundraising', 'total_points'] },
  { type: '*', opportunity_name_pattern: '2025 Par 3 - Prize Donation', routing: 'dollars',
    routing_metrics: ['total_fundraising', 'total_points'] },
];

const PATTERNS: CreditRoutingPattern[] = [
  { pattern: 'Rate Bowl', routing_metrics: ['total_fundraising', 'rate_bowl', 'total_points'], sort_order: 10 },
  { pattern: 'Wishes',    routing_metrics: ['total_fundraising', 'wishes_for_teachers', 'total_points'], sort_order: 20 },
];

/**
 * Build a credit-export xlsx mirroring the 2026-05-22 production v2.0 shape:
 *   - R2 title, R3 generated-by
 *   - R9: left-block close-date filter (Custom (MM/DD/YYYY to MM/DD/YYYY))
 *   - R11: left-block team filter (comma-joined)
 *   - R14: right-block planned-start filter
 *   - R16: right-block team filter
 *   - R19: block-label row
 *   - R20: header row
 *   - R21+: data rows
 */
function buildCreditXlsx(args: {
  outPath: string;
  title: string;
  opportunitiesDateRange: string; // 'MM/DD/YYYY to MM/DD/YYYY'
  pointsDateRange?: string;
  teamFilterLeft: string;   // comma-joined
  teamFilterRight?: string; // defaults to teamFilterLeft
  leftRows: Array<{ fcid: string; name: string; opp: string; amt: number; type: string }>;
  rightRows?: Array<{ fcid: string; name: string; job: string; pts: number; campaign: string }>;
}): void {
  const grid: unknown[][] = [];
  grid.push([]);                                                                                       // R1
  grid.push([null, args.title]);                                                                       // R2
  grid.push([null, `As of 2026-05-22 11:40:54 MST • Generated by test`]);                              // R3
  grid.push([]); grid.push([]);                                                                        // R4 R5
  grid.push([null, 'Filtered By']);                                                                    // R6
  grid.push([null, 'Yellow Jacket Credit- Opportunities']);                                            // R7
  grid.push([null, 'Show: All accounts']);                                                             // R8
  grid.push([null, `Date Field: Opportunity: Close Date equals Custom (${args.opportunitiesDateRange})`]); // R9
  grid.push([null, 'Account Name contains Yellow Jacket']);                                            // R10
  grid.push([null, `Yellow Jacket Team equals ${args.teamFilterLeft}`]);                               // R11
  grid.push([null, 'Volunteer Points']);                                                               // R12
  grid.push([null, 'Show: All accounts']);                                                             // R13
  grid.push([null, `Date Field: Planned Start Date & Time equals Custom (${args.pointsDateRange ?? args.opportunitiesDateRange})`]); // R14
  grid.push([null, 'Account Name contains Yellow Jacket']);                                            // R15
  grid.push([null, `Yellow Jacket Team equals ${args.teamFilterRight ?? args.teamFilterLeft}`]);       // R16
  grid.push([]);                                                                                       // R17
  grid.push([null, 'Contacts with Custom Object', null, null, null, null, 'Contacts with Custom Object']); // R18
  grid.push([null, 'Yellow Jacket Credit- Opportunities', null, null, null, null, 'Volunteer Points']);// R19
  grid.push([]);                                                                                       // R20 separator
  // Header — production v2 column order: Contact Full Name | Full Contact ID | ...
  grid.push([
    null,
    'Contact Full Name', null, 'Full Contact ID', 'Opportunity: Opportunity Name', 'Amount Credited', 'Type',
    'Contact Full Name', 'Full Contact ID', 'Volunteer Job: Volunteer Job Name', 'Volunteer Points', 'Volunteer Job: Campaign',
  ]);

  const right = args.rightRows ?? [];
  const maxRows = Math.max(args.leftRows.length, right.length);
  for (let i = 0; i < maxRows; i++) {
    const l = args.leftRows[i];
    const r = right[i];
    grid.push([
      null,
      l?.name ?? null, null, l?.fcid ?? null, l?.opp ?? null, l?.amt ?? null, l?.type ?? null,
      r?.name ?? null, r?.fcid ?? null, r?.job ?? null, r?.pts ?? null, r?.campaign ?? null,
    ]);
  }
  grid.push([null, 'Total', null, null, null, 0, null, null, null, null, 0, null]);
  grid.push([null, 'Confidential Information - Do Not Distribute']);

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(grid), 'Sheet1');
  XLSX.writeFile(wb, args.outPath);
}

// ─── Tests ────────────────────────────────────────────────────────────────

describe('Multi-team filter parsing', () => {
  it('extracts both teams from filter rows 11 + 16 (union)', () => {
    const path = resolve(TMP, '2026-27 Active YJ - 1.0-2026-05-22-12-00-00.xlsx');
    buildCreditXlsx({
      outPath: path,
      title: '2026-27 Active YJ - 1.0',
      opportunitiesDateRange: '1/1/2026 to 12/31/2026',
      teamFilterLeft: 'Cobbers,Fighting Camels',
      leftRows: [
        { fcid: 'C001', name: 'Alice Acorn', opp: '2025 FKE Paddle Raise', amt: 600, type: 'Cash' },
      ],
    });
    const roster = makeRoster([
      row({ full_contact_id: 'C001', sales_rep_id: 1001, full_name: 'Alice Acorn', team: 'Cobbers' }),
    ]);
    const errors = new IngestErrorCollector();
    const result = parseVolunteerCredit({
      creditPath: path,
      roster,
      cashRoutingAllowlist: SEEDS_BASE,
      routingPatterns: PATTERNS,
      errors,
    });
    expect(result.metadata.teams_in_filter).toEqual(['Cobbers', 'Fighting Camels']);
    // Date range parsed.
    expect(result.metadata.opportunities_date_range).toEqual({ start: '2026-01-01', end: '2026-12-31' });
    // No team-disagreement warning (row 11 and row 16 match).
    expect(errors.all().find((e) => e.kind === 'credit_filter_team_disagreement')).toBeUndefined();
    rmSync(path);
  });

  it('emits credit_filter_team_disagreement when row 11 ≠ row 16, uses union', () => {
    const path = resolve(TMP, 'disagree.xlsx');
    buildCreditXlsx({
      outPath: path,
      title: '2026-27 Active YJ - 1.0',
      opportunitiesDateRange: '1/1/2026 to 12/31/2026',
      teamFilterLeft: 'Cobbers',
      teamFilterRight: 'Fighting Camels',
      leftRows: [
        { fcid: 'C001', name: 'Alice', opp: '2025 FKE Paddle Raise', amt: 100, type: 'Cash' },
      ],
    });
    const roster = makeRoster([
      row({ full_contact_id: 'C001', sales_rep_id: 1, full_name: 'Alice', team: 'Cobbers' }),
    ]);
    const errors = new IngestErrorCollector();
    const result = parseVolunteerCredit({
      creditPath: path, roster, cashRoutingAllowlist: SEEDS_BASE, routingPatterns: PATTERNS, errors,
    });
    expect(result.metadata.teams_in_filter.sort()).toEqual(['Cobbers', 'Fighting Camels']);
    const disagree = errors.all().filter((e) => e.kind === 'credit_filter_team_disagreement');
    expect(disagree.length).toBe(1);
    rmSync(path);
  });
});

describe('file_team_mismatch — per-row check against teams_in_filter', () => {
  it('fires when volunteer roster team is not in the filter set; credit still flows', () => {
    const path = resolve(TMP, 'mismatch.xlsx');
    buildCreditXlsx({
      outPath: path,
      title: '2026-27 Active YJ - 1.0',
      opportunitiesDateRange: '1/1/2026 to 12/31/2026',
      teamFilterLeft: 'Cobbers',
      leftRows: [
        { fcid: 'C001', name: 'Alice', opp: '2025 FKE Paddle Raise', amt: 500, type: 'Cash' },
      ],
    });
    // Alice's roster team is 'Pistol Petes', NOT in the file's filter set.
    const roster = makeRoster([
      row({ full_contact_id: 'C001', sales_rep_id: 1, full_name: 'Alice', team: 'Pistol Petes' }),
    ]);
    const errors = new IngestErrorCollector();
    const result = parseVolunteerCredit({
      creditPath: path, roster, cashRoutingAllowlist: SEEDS_BASE, routingPatterns: PATTERNS, errors,
    });
    expect(result.records.length).toBe(1);
    const ftm = errors.all().filter((e) => e.kind === 'file_team_mismatch');
    expect(ftm.length).toBe(1);
    rmSync(path);
  });
});

describe('Multi-dimensional routing — seed + pattern + Type fallback', () => {
  function runSingleRow(args: {
    opp: string;
    type: string;
    amt: number;
  }): { errors: IngestErrorCollector; tf: number; rb: number; w: number; pts: number } {
    const path = resolve(TMP, `single_${args.opp.replace(/\W+/g, '_')}_${args.type}.xlsx`);
    buildCreditXlsx({
      outPath: path,
      title: '2026-27 Active YJ - 1.0',
      opportunitiesDateRange: '1/1/2026 to 12/31/2026',
      teamFilterLeft: 'Cobbers',
      leftRows: [{ fcid: 'C001', name: 'Alice', opp: args.opp, amt: args.amt, type: args.type }],
    });
    const roster = makeRoster([
      row({ full_contact_id: 'C001', sales_rep_id: 1, full_name: 'Alice', team: 'Cobbers' }),
    ]);
    const errors = new IngestErrorCollector();
    const { records } = parseVolunteerCredit({
      creditPath: path, roster, cashRoutingAllowlist: SEEDS_BASE, routingPatterns: PATTERNS, errors,
    });
    const out = computeMetrics({
      unifyAllocations: [], creditRecords: records, exceptions: [], roster, errors,
    });
    const alice = out.volunteers.find((v) => v.id === 'C001')!;
    rmSync(path);
    return {
      errors,
      tf: alice.metrics.totalFundraising,
      rb: alice.metrics.rateBowl,
      w: alice.metrics.wishesForTeachers,
      pts: alice.metrics.totalPoints,
    };
  }

  it('Race for Wishes Cash routes to totalFundraising + wishesForTeachers + totalPoints', () => {
    const r = runSingleRow({ opp: 'Race for Wishes', type: 'Cash', amt: 104 });
    expect(r.tf).toBe(104);
    expect(r.w).toBe(104);
    expect(r.pts).toBe(104);
    expect(r.rb).toBe(0);
  });

  it('Race for Wishes Sponsorship routes the same as Cash (Type ignored for exact seed match)', () => {
    const r = runSingleRow({ opp: 'Race for Wishes', type: 'Sponsorship', amt: 500 });
    expect(r.tf).toBe(500);
    expect(r.w).toBe(500);
    expect(r.pts).toBe(500);
    expect(r.rb).toBe(0);
  });

  it('hypothetical Rate Bowl Title Sponsor (Sponsorship) hits rate_bowl via pattern', () => {
    const r = runSingleRow({ opp: 'Rate Bowl Title Sponsor', type: 'Sponsorship', amt: 50000 });
    expect(r.tf).toBe(50000);
    expect(r.rb).toBe(50000);
    expect(r.pts).toBe(50000);
    expect(r.w).toBe(0);
  });

  it('"Wishes Spring Bash" (no seed, matches Wishes pattern) hits wishes_for_teachers', () => {
    const r = runSingleRow({ opp: 'Wishes Spring Bash', type: 'Cash', amt: 200 });
    expect(r.tf).toBe(200);
    expect(r.w).toBe(200);
    expect(r.pts).toBe(200);
    expect(r.rb).toBe(0);
  });

  it('In-Kind with unknown name falls back to [total_fundraising, total_points]', () => {
    const r = runSingleRow({ opp: 'Random Auction Item', type: 'In-Kind', amt: 800 });
    expect(r.tf).toBe(800);
    expect(r.pts).toBe(800);
    expect(r.rb).toBe(0);
    expect(r.w).toBe(0);
    // No error.
    expect(r.errors.errorCount()).toBe(0);
  });

  it('Cash with unknown name emits unallowlisted_opportunity_name and drops the row', () => {
    const r = runSingleRow({ opp: 'Mystery Cash', type: 'Cash', amt: 50 });
    expect(r.tf).toBe(0);
    expect(r.errors.all().filter((e) => e.kind === 'unallowlisted_opportunity_name').length).toBe(1);
  });

  it('In-Kind Prize Donation routes at full face value (no cap)', () => {
    const r = runSingleRow({ opp: '2025 Par 3 - Prize Donation', type: 'In-Kind', amt: 48000 });
    expect(r.tf).toBe(48000);
    expect(r.pts).toBe(48000);
    expect(r.rb).toBe(0);
  });

  it('Exact seed wins over Wishes pattern (Race for Wishes hits seed, not pattern fallback)', () => {
    // Verified above — Race for Wishes seed yields w:104. If pattern took
    // precedence the result would be identical here, so the more meaningful
    // check is the orchestrator log path. This test pins the behavior under
    // both seeds AND a pattern that would also match.
    const r = runSingleRow({ opp: 'Race for Wishes', type: 'Cash', amt: 100 });
    expect(r.tf).toBe(100);
    expect(r.w).toBe(100);
  });

  it('does not double-count when routing_metrics has duplicate entries', () => {
    const path = resolve(TMP, 'dup_metrics.xlsx');
    buildCreditXlsx({
      outPath: path,
      title: '2026-27 Active YJ - 1.0',
      opportunitiesDateRange: '1/1/2026 to 12/31/2026',
      teamFilterLeft: 'Cobbers',
      leftRows: [{ fcid: 'C001', name: 'Alice', opp: 'Custom Op', amt: 100, type: 'Sponsorship' }],
    });
    const roster = makeRoster([
      row({ full_contact_id: 'C001', sales_rep_id: 1, full_name: 'Alice', team: 'Cobbers' }),
    ]);
    const errors = new IngestErrorCollector();
    // Seed with a malformed duplicate routing_metrics.
    const seeds: CashRoutingRule[] = [
      { type: '*', opportunity_name_pattern: 'Custom Op', routing: 'dollars',
        // duplicates intentional
        routing_metrics: ['total_fundraising', 'total_fundraising', 'total_points'] },
    ];
    const { records } = parseVolunteerCredit({
      creditPath: path, roster, cashRoutingAllowlist: seeds, routingPatterns: [], errors,
    });
    const out = computeMetrics({
      unifyAllocations: [], creditRecords: records, exceptions: [], roster, errors,
    });
    const alice = out.volunteers.find((v) => v.id === 'C001')!;
    // Should be 100, not 200.
    expect(alice.metrics.totalFundraising).toBe(100);
    expect(alice.metrics.totalPoints).toBe(100);
    rmSync(path);
  });
});

describe('Historical-baseline detection + ingest', () => {
  it('isHistoricalFile classifies pre-season files as historical', () => {
    expect(isHistoricalFile({ opportunitiesDateRangeEnd: '2025-12-31', seasonYear: 2026 })).toBe(true);
    expect(isHistoricalFile({ opportunitiesDateRangeEnd: '2026-01-01', seasonYear: 2026 })).toBe(false);
    expect(isHistoricalFile({ opportunitiesDateRangeEnd: '2026-06-30', seasonYear: 2026 })).toBe(false);
    expect(isHistoricalFile({ opportunitiesDateRangeEnd: null, seasonYear: 2026 })).toBe(false);
  });

  it('historical-period file populates last_year_* on the roster; metrics.totalFundraising stays zero', () => {
    const path = resolve(TMP, '2025-26 Active YJ - 2.0-2026-05-22-11-40-54.xlsx');
    buildCreditXlsx({
      outPath: path,
      title: '2025-26 Active YJ - 2.0',
      opportunitiesDateRange: '12/9/2024 to 12/31/2025',
      pointsDateRange: '12/23/2024 to 12/22/2025',
      teamFilterLeft: 'Cobbers,Fighting Camels',
      leftRows: [
        { fcid: 'C001', name: 'Alice', opp: '2025 FKE Paddle Raise', amt: 600,  type: 'Cash' },
        { fcid: 'C001', name: 'Alice', opp: 'Race for Wishes',       amt: 100,  type: 'Cash' },
        { fcid: 'C002', name: 'Bob',   opp: '2025 FKE Paddle Raise', amt: 3000, type: 'Cash' },
        { fcid: 'C003', name: 'Carla', opp: 'Race for Wishes',       amt: 52,   type: 'Cash' },
      ],
    });
    const roster = makeRoster([
      row({ full_contact_id: 'C001', sales_rep_id: 1, full_name: 'Alice', team: 'Cobbers' }),
      row({ full_contact_id: 'C002', sales_rep_id: 2, full_name: 'Bob',   team: 'Fighting Camels' }),
      row({ full_contact_id: 'C003', sales_rep_id: 3, full_name: 'Carla', team: 'Cobbers' }),
    ]);
    const errors = new IngestErrorCollector();
    const { records, metadata } = parseVolunteerCredit({
      creditPath: path, roster, cashRoutingAllowlist: SEEDS_BASE, routingPatterns: PATTERNS, errors,
    });
    expect(metadata.opportunities_date_range?.end).toBe('2025-12-31');
    expect(isHistoricalFile({
      opportunitiesDateRangeEnd: metadata.opportunities_date_range?.end ?? null,
      seasonYear: 2026,
    })).toBe(true);

    computeHistoricalBaseline({ creditRecords: records, roster, errors });

    // Per-FCID baseline check.
    expect(roster.by_full_contact_id.get('C001')!.last_year_fundraising_dollars).toBe(700);  // 600 + 100
    expect(roster.by_full_contact_id.get('C002')!.last_year_fundraising_dollars).toBe(3000);
    expect(roster.by_full_contact_id.get('C003')!.last_year_fundraising_dollars).toBe(52);

    // Rank: Bob (3000) → 1, Alice (700) → 2, Carla (52) → 3.
    expect(roster.by_full_contact_id.get('C002')!.last_year_fundraising_rank).toBe(1);
    expect(roster.by_full_contact_id.get('C001')!.last_year_fundraising_rank).toBe(2);
    expect(roster.by_full_contact_id.get('C003')!.last_year_fundraising_rank).toBe(3);

    // Current-season metrics MUST be untouched.
    const out = computeMetrics({
      unifyAllocations: [], creditRecords: [], exceptions: [], roster, errors,
    });
    const alice = out.volunteers.find((v) => v.id === 'C001')!;
    expect(alice.metrics.totalFundraising).toBe(0);
    expect(alice.metrics.wishesForTeachers).toBe(0);
    expect(alice.metrics.totalPoints).toBe(0);
    // Historical values still surface on the VolunteerOutput.
    expect(alice.last_year_fundraising_dollars).toBe(700);
    expect(alice.last_year_fundraising_rank).toBe(2);
    rmSync(path);
  });

  it('current-period file routes credits to metrics.totalFundraising as before', () => {
    const path = resolve(TMP, 'current_season.xlsx');
    buildCreditXlsx({
      outPath: path,
      title: '2026-27 Active YJ - 1.0',
      opportunitiesDateRange: '1/1/2026 to 12/31/2026',
      teamFilterLeft: 'Cobbers',
      leftRows: [
        { fcid: 'C001', name: 'Alice', opp: '2025 FKE Paddle Raise', amt: 600, type: 'Cash' },
      ],
    });
    const roster = makeRoster([
      row({ full_contact_id: 'C001', sales_rep_id: 1, full_name: 'Alice', team: 'Cobbers' }),
    ]);
    const errors = new IngestErrorCollector();
    const { records, metadata } = parseVolunteerCredit({
      creditPath: path, roster, cashRoutingAllowlist: SEEDS_BASE, routingPatterns: PATTERNS, errors,
    });
    expect(isHistoricalFile({
      opportunitiesDateRangeEnd: metadata.opportunities_date_range?.end ?? null,
      seasonYear: 2026,
    })).toBe(false);

    const out = computeMetrics({
      unifyAllocations: [], creditRecords: records, exceptions: [], roster, errors,
    });
    const alice = out.volunteers.find((v) => v.id === 'C001')!;
    expect(alice.metrics.totalFundraising).toBe(600);
    expect(alice.last_year_fundraising_dollars).toBeNull();
    rmSync(path);
  });

  it('Codex DIM-2 — two historical files for the same prior season do not double-count (latest wins)', () => {
    const p1 = resolve(TMP, 'hist_v1.xlsx');
    const p2 = resolve(TMP, 'hist_v2.xlsx');
    // Same data row, two different timestamped files. With Codex DIM-2 fix,
    // only the latest batch counts toward last_year_*.
    buildCreditXlsx({
      outPath: p1,
      title: '2025-26 Active YJ - 1.0',
      opportunitiesDateRange: '1/1/2025 to 12/31/2025',
      teamFilterLeft: 'Cobbers',
      leftRows: [
        { fcid: 'C001', name: 'Alice', opp: '2025 FKE Paddle Raise', amt: 600, type: 'Cash' },
      ],
    });
    // Rename p1 to embed an earlier timestamp.
    const earlier = resolve(TMP, 'hist-2026-05-01-09-00-00.xlsx');
    const later   = resolve(TMP, 'hist-2026-05-22-09-00-00.xlsx');
    renameSync(p1, earlier);
    buildCreditXlsx({
      outPath: p2,
      title: '2025-26 Active YJ - 2.0',
      opportunitiesDateRange: '1/1/2025 to 12/31/2025',
      teamFilterLeft: 'Cobbers',
      leftRows: [
        { fcid: 'C001', name: 'Alice', opp: '2025 FKE Paddle Raise', amt: 800, type: 'Cash' }, // amended amount
      ],
    });
    renameSync(p2, later);

    const roster = makeRoster([
      row({ full_contact_id: 'C001', sales_rep_id: 1, full_name: 'Alice', team: 'Cobbers' }),
    ]);
    const errors = new IngestErrorCollector();
    const { records: r1 } = parseVolunteerCredit({
      creditPath: earlier, roster, cashRoutingAllowlist: SEEDS_BASE, routingPatterns: PATTERNS, errors,
    });
    const { records: r2 } = parseVolunteerCredit({
      creditPath: later, roster, cashRoutingAllowlist: SEEDS_BASE, routingPatterns: PATTERNS, errors,
    });
    computeHistoricalBaseline({ creditRecords: [...r1, ...r2], roster, errors });
    // Only the later batch's $800 should land, not 600+800=1400.
    expect(roster.by_full_contact_id.get('C001')!.last_year_fundraising_dollars).toBe(800);
    rmSync(earlier); rmSync(later);
  });

  it('Codex DIM-3 — explicit ignore seed short-circuits (no pattern/Type fallback)', () => {
    const path = resolve(TMP, 'ignore_seed.xlsx');
    buildCreditXlsx({
      outPath: path,
      title: '2026-27 Active YJ - 1.0',
      opportunitiesDateRange: '1/1/2026 to 12/31/2026',
      teamFilterLeft: 'Cobbers',
      leftRows: [
        // Name contains "Wishes" — would normally hit the Wishes pattern.
        { fcid: 'C001', name: 'Alice', opp: 'Refund Wishes Adjustment', amt: 200, type: 'Sponsorship' },
      ],
    });
    const seeds: CashRoutingRule[] = [
      // Explicit ignore for the exact name. Must beat the Wishes pattern.
      { type: '*', opportunity_name_pattern: 'Refund Wishes Adjustment', routing: 'ignore',
        routing_metrics: [] },
    ];
    const roster = makeRoster([
      row({ full_contact_id: 'C001', sales_rep_id: 1, full_name: 'Alice', team: 'Cobbers' }),
    ]);
    const errors = new IngestErrorCollector();
    const { records } = parseVolunteerCredit({
      creditPath: path, roster, cashRoutingAllowlist: seeds, routingPatterns: PATTERNS, errors,
    });
    expect(records.length).toBe(0); // ignored row produces no record
    expect(errors.errorCount()).toBe(0);
    rmSync(path);
  });

  it('Codex DIM-6 — global supersession across mixed legacy + multi-team files', () => {
    // One legacy single-team file (Gorlocks-{ts}.xlsx) earlier in time,
    // one multi-team file (Active YJ {ts}.xlsx) later. The multi-team file
    // must globally supersede the legacy one.
    const legacyPath = resolve(TMP, 'Gorlocks-2026-05-01-09-00-00.xlsx');
    buildCreditXlsx({
      outPath: legacyPath,
      title: 'Gorlocks Credit',
      opportunitiesDateRange: '1/1/2026 to 12/31/2026',
      teamFilterLeft: 'Gorlocks',
      leftRows: [
        { fcid: 'C001', name: 'Alice', opp: '2025 FKE Paddle Raise', amt: 1000, type: 'Cash' },
      ],
    });
    const multiPath = resolve(TMP, '2026-27 Active YJ - 1.0-2026-05-22-09-00-00.xlsx');
    buildCreditXlsx({
      outPath: multiPath,
      title: '2026-27 Active YJ - 1.0',
      opportunitiesDateRange: '1/1/2026 to 12/31/2026',
      teamFilterLeft: 'Gorlocks,Cobbers',
      leftRows: [
        { fcid: 'C001', name: 'Alice', opp: '2025 FKE Paddle Raise', amt: 250, type: 'Cash' },
      ],
    });
    const roster = makeRoster([
      row({ full_contact_id: 'C001', sales_rep_id: 1, full_name: 'Alice', team: 'Gorlocks' }),
    ]);
    const errors = new IngestErrorCollector();
    const { records: rLegacy } = parseVolunteerCredit({
      creditPath: legacyPath, roster, cashRoutingAllowlist: SEEDS_BASE, routingPatterns: PATTERNS, errors,
    });
    const { records: rMulti } = parseVolunteerCredit({
      creditPath: multiPath, roster, cashRoutingAllowlist: SEEDS_BASE, routingPatterns: PATTERNS, errors,
    });
    const out = computeMetrics({
      unifyAllocations: [], creditRecords: [...rLegacy, ...rMulti], exceptions: [], roster, errors,
    });
    const alice = out.volunteers.find((v) => v.id === 'C001')!;
    // Only the later $250 (from the multi-team file) should land, not $1250.
    expect(alice.metrics.totalFundraising).toBe(250);
    rmSync(legacyPath); rmSync(multiPath);
  });

  it('roster_baseline_overridden fires when roster has a different last-year value', () => {
    const path = resolve(TMP, 'override.xlsx');
    buildCreditXlsx({
      outPath: path,
      title: '2025-26 Active YJ - 2.0',
      opportunitiesDateRange: '12/9/2024 to 12/31/2025',
      teamFilterLeft: 'Cobbers',
      leftRows: [
        { fcid: 'C001', name: 'Alice', opp: '2025 FKE Paddle Raise', amt: 700, type: 'Cash' },
      ],
    });
    const roster = makeRoster([
      row({
        full_contact_id: 'C001', sales_rep_id: 1, full_name: 'Alice',
        team: 'Cobbers',
        last_year_fundraising_dollars: 999,
      }),
    ]);
    const errors = new IngestErrorCollector();
    const { records } = parseVolunteerCredit({
      creditPath: path, roster, cashRoutingAllowlist: SEEDS_BASE, routingPatterns: PATTERNS, errors,
    });
    computeHistoricalBaseline({ creditRecords: records, roster, errors });
    expect(roster.by_full_contact_id.get('C001')!.last_year_fundraising_dollars).toBe(700);
    const overrides = errors.all().filter((e) => e.kind === 'roster_baseline_overridden');
    expect(overrides.length).toBe(1);
    rmSync(path);
  });
});
